server:
  port: 9090
spring:
  datasource:
    url: jdbc:h2:file:./data/recipecollection;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
logging:
  level:
    org.hibernate.SQL: debug
jwt:
  secret: "replace-with-a-secure-secret-key"
  issuer: "recipecollection"
  audience: "recipecollection"
  expiration-ms: 3600000
